#!/usr/bin/env python3
"""Writes typed definitions of the socket API from schema/ (see docs/WRITING.md, "Typed
definitions from the schema").

    python3 scripts/gen-types.py                       # TypeScript to stdout
    python3 scripts/gen-types.py --lang python         # ts python go csharp rust java
    python3 scripts/gen-types.py --lang go -o al.go    # to a file
    python3 scripts/gen-types.py --all DIR             # every language into DIR/<lang>/...

All seven languages render the same list of declarations, `apischema.model(schema)`: the named
types of schema/types.json and of the event files, then per event you send its request (a
discriminated union for an event with variants), each reply, and its failure union, then per
event you receive its payload. TypeScript is in apischema.py (`typescript()`); the six others are
here. scripts/check-types.py compiles each output in Docker (tsc --strict, mypy --strict,
go vet + go build, dotnet build, cargo build, mvn compile).

How the schema maps (the table in docs/WRITING.md):

- An object type becomes a TypedDict / struct / record. A type that `extends` another gets the
  base fields copied in (flattened): Python TypedDicts cannot narrow an inherited field, Go and
  Rust have no inheritance, and Java records cannot extend. A field of the type replaces the
  base field of the same name.
- A literal becomes its primitive (`"buy"` -> string) except in Python (`Literal["buy"]`); a
  union of literals of one primitive becomes that primitive; `T | null` becomes an optional /
  nullable T.
- A union of different shapes becomes the language's "any JSON" type (json.RawMessage,
  JsonElement, serde_json::Value, JsonNode), except in Python (a real union) and Rust (an
  `#[serde(untagged)]` enum for the unions the model declares: requests and failures).
- `integer` / `number` become int / float (int64 / float64, long / double, i64 / f64).
- Optional fields: NotRequired (Python), pointer + omitempty (Go), nullable (C#, Java),
  Option + skip_serializing_if (Rust).
"""

import json
import keyword
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import apischema  # noqa: E402  (the path insert above makes the repo root importable)
from apischema import parse_type, pascal  # noqa: E402

LANGS = ["ts", "python", "go", "csharp", "rust", "java"]
# Where --all writes each language: (file, extra project files are written by check-types.py).
FILES = {"ts": "al-api.ts", "python": "al_api.py", "go": "alapi/alapi.go",
         "csharp": "AlApi.cs", "rust": "src/al_api.rs", "java": "src/main/java/alapi/AlApi.java"}
HEADER = "Generated by scripts/gen-types.py from schema/. Do not edit by hand."


# ---------------------------------------------------------------------------------------------
# Shared helpers: flattening, primitive analysis, names
# ---------------------------------------------------------------------------------------------


class Lang:
    """What every language generator shares: the model, the flattened fields of each object
    declaration, and the analysis of type trees."""

    def __init__(self, schema):
        self.schema = schema
        self.m = apischema.model(schema)
        self.objects = {n: b for k, n, d, b in self.m.decls if k == "object"}
        self.aliases = {n: b for k, n, d, b in self.m.decls if k == "alias"}
        self.unions = {n: b for k, n, d, b in self.m.decls if k == "union"}

    def fields(self, body):
        """The fields of an object declaration, the base fields first (flattened)."""
        base = []
        if body.get("extends"):
            base = self.fields(self.objects[body["extends"]])
        own = body["fields"]
        names = {f["name"] for f in own}
        return [f for f in base if f["name"] not in names] + own

    def is_open(self, body):
        return body["open"] or bool(body.get("extends") and self.is_open(self.objects[body["extends"]]))

    def target(self, name, seen=()):
        """What a declared name stands for: ("object", name), ("prim", p), ("tree", tree) for an
        alias, ("union", name) for a declared union."""
        if name in self.objects:
            return ("object", name)
        if name in self.unions:
            return ("union", name)
        if name in self.aliases and name not in seen:
            return ("tree", parse_type(self.aliases[name]))
        return ("prim", "any")

    def prim(self, tree, seen=()):
        """The one primitive a tree always is ("string", "integer", "number", "boolean", "null"),
        through aliases and unions of literals; None when it is not one primitive."""
        kind = tree[0]
        if kind == "lit":
            v = tree[1]
            return "boolean" if isinstance(v, bool) else "string" if isinstance(v, str) else \
                "integer" if isinstance(v, int) else "number"
        if kind == "prim":
            return tree[1] if tree[1] in ("string", "integer", "number", "boolean", "null") else None
        if kind == "ref":
            if tree[1] in seen:
                return None
            t = self.target(tree[1])
            return self.prim(t[1], seen + (tree[1],)) if t[0] == "tree" else None
        if kind == "union":
            ps = {self.prim(t, seen) for t in tree[1]}
            if None in ps:
                return None
            if ps == {"integer", "number"}:
                return "number"
            return ps.pop() if len(ps) == 1 else None
        return None

    @staticmethod
    def split_null(tree):
        """(tree without null, nullable?) for `T | null`."""
        if tree[0] == "union" and ("prim", "null") in tree[1]:
            rest = [t for t in tree[1] if t != ("prim", "null")]
            return (rest[0] if len(rest) == 1 else ("union", rest)), True
        return tree, False


def doc_text(text):
    return re.sub(r"\s+", " ", text or "").strip()


def wrap(text, width=96, prefix=""):
    """A comment block, wrapped."""
    words, lines, line = doc_text(text).split(" "), [], ""
    for w in words:
        if line and len(line) + 1 + len(w) > width - len(prefix):
            lines.append(line)
            line = w
        else:
            line = f"{line} {w}" if line else w
    if line:
        lines.append(line)
    return [prefix + x for x in lines] or [prefix.rstrip()]


def unique_names(names, make, reserved=()):
    """Maps each JSON key to an identifier made by `make`, unique within one type."""
    out, taken = {}, set(reserved)
    for n in names:
        ident = make(n)
        while ident in taken:
            ident += "_"
        taken.add(ident)
        out[n] = ident
    return out


# ---------------------------------------------------------------------------------------------
# Python: TypedDict (functional syntax, so keys such as "in" and "1hp" work), checked by mypy
# ---------------------------------------------------------------------------------------------


class Python(Lang):
    def t(self, tree):
        kind = tree[0]
        if kind == "prim":
            return {"string": "str", "integer": "int", "number": "float", "boolean": "bool",
                    "null": "None", "any": "Any", "object": "dict[str, Any]"}[tree[1]]
        if kind == "lit":
            return f"Literal[{json.dumps(tree[1]) if not isinstance(tree[1], bool) else tree[1]}]"
        if kind == "ref":
            return tree[1]
        if kind == "array":
            return f"list[{self.t(tree[1])}]"
        if kind == "record":
            return f"dict[str, {self.t(tree[1])}]"
        if kind == "tuple":
            return "tuple[" + ", ".join(self.t(x) for x in tree[1]) + "]"
        if kind == "union":
            lits = [x[1] for x in tree[1] if x[0] == "lit"]
            rest = [self.t(x) for x in tree[1] if x[0] != "lit"]
            parts = ([f"Literal[{', '.join(json.dumps(v) if not isinstance(v, bool) else str(v) for v in lits)}]"]
                     if lits else []) + rest
            return " | ".join(dict.fromkeys(parts))
        raise ValueError(tree)

    def render(self):
        out = [f"# {HEADER}", "# Each type is a TypedDict (functional syntax: some JSON keys are Python keywords).",
               "# The annotations are strings, so the order of the definitions does not matter.",
               "from __future__ import annotations", "",
               "from typing import Any, Literal, TypedDict", "",
               "from typing_extensions import NotRequired, TypeAlias", ""]
        for kind, name, doc, body in self.m.decls:
            out += wrap(doc, prefix="# ")
            if kind == "object":
                items = []
                for f in self.fields(body):
                    t = self.t(parse_type(f["type"]))
                    if f.get("optional"):
                        t = f"NotRequired[{t}]"
                    items.append(f"    {json.dumps(f['name'])}: {json.dumps(t)},")
                if self.is_open(body):
                    out.append("# The object can have more keys than these (a TypedDict cannot say so).")
                out.append(f"{name} = TypedDict({json.dumps(name)}, {{" + ("\n" + "\n".join(items) + "\n" if items else "") + "})")
            elif kind == "alias":
                out.append(f"{name}: TypeAlias = {json.dumps(self.t(parse_type(body)))}")
            else:
                out.append(f"{name}: TypeAlias = {json.dumps(' | '.join(self.t(parse_type(x)) for x in body))}")
            out.append("")
        # The event maps, as plain dicts of names (Python has no type-level map).
        out.append("# Client to server: event name -> the request type name (None: no payload).")
        out.append("CLIENT_EVENTS: dict[str, str | None] = {")
        out += [f"    {json.dumps(e)}: {json.dumps(t) if t else None}," for e, t in self.m.client]
        out.append("}")
        out.append("# Server to client: event name -> the payload type name.")
        out.append("SERVER_EVENTS: dict[str, str] = {")
        out += [f"    {json.dumps(e)}: {json.dumps(t)}," for e, t in self.m.server.items()]
        out.append("}")
        return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# Go: structs with json tags; a union of shapes is json.RawMessage
# ---------------------------------------------------------------------------------------------


def go_ident(name):
    p = pascal(name)
    if not p or not p[0].isalpha():
        p = "X" + p
    return p


class Go(Lang):
    PRIM = {"string": "string", "integer": "int64", "number": "float64", "boolean": "bool",
            "null": "any", "any": "any", "object": "map[string]any"}

    def t(self, tree):
        tree, _ = self.split_null(tree)
        p = self.prim(tree)
        if p:
            return self.PRIM[p]
        kind = tree[0]
        if kind == "prim":
            return self.PRIM[tree[1]]
        if kind == "ref":
            return tree[1]
        if kind == "array":
            return "[]" + self.t(tree[1])
        if kind == "record":
            return "map[string]" + self.t(tree[1])
        if kind == "tuple":
            return "[]any"  # a JSON array of mixed values
        return "json.RawMessage"  # a union of shapes: decode by hand

    def field_type(self, f):
        tree, nullable = self.split_null(parse_type(f["type"]))
        t = self.t(tree)
        # Optional and nullable scalars and structs become pointers, so "absent" is nil. Slices,
        # maps and raw JSON are nil already. Named structs are always pointers: a struct that
        # holds itself through a chain of fields would otherwise have infinite size.
        if t.startswith(("[]", "map[")) or t in ("any", "json.RawMessage"):
            return t
        if t in self.objects or f.get("optional") or nullable:
            return "*" + t
        return t

    def render(self):
        out = [f"// {HEADER}", "", "// Package alapi holds the types of the Adventure Land socket API.",
               "package alapi", "", 'import "encoding/json"', "",
               "// RawJSON keeps the import used when no type needs it.", "type RawJSON = json.RawMessage", ""]
        for kind, name, doc, body in self.m.decls:
            out += wrap(f"{name}: {doc}", prefix="// ")
            if kind == "object":
                fs = self.fields(body)
                idents = unique_names([f["name"] for f in fs], go_ident, {"Extra"})
                out.append(f"type {name} struct {{")
                for f in fs:
                    tag = f["name"] + (",omitempty" if f.get("optional") else "")
                    out.append(f"\t{idents[f['name']]} {self.field_type(f)} `json:{json.dumps(tag)}`")
                if self.is_open(body):
                    out.append("\t// Extra holds the keys this struct does not name (needs a custom UnmarshalJSON).")
                    out.append('\tExtra map[string]json.RawMessage `json:"-"`')
                out.append("}")
            elif kind == "alias":
                tree = parse_type(body)
                t = self.t(tree)
                if t == name:
                    t = "json.RawMessage"
                out.append(f"type {name} = {t}")
            else:
                out.append("// One of: " + ", ".join(body) + ".")
                p = self.prim(("union", [parse_type(x) for x in body]))
                out.append(f"type {name} = {self.PRIM[p] if p else 'json.RawMessage'}")
            out.append("")
        return "\n".join(out)


# ---------------------------------------------------------------------------------------------
# C#: records for System.Text.Json; aliases are inlined (C# has no file-wide type alias that
# can name another alias)
# ---------------------------------------------------------------------------------------------

CS_KEYWORDS = set("""abstract as base bool break byte case catch char checked class const continue
decimal default delegate do double else enum event explicit extern false finally fixed float for
foreach goto if implicit in int interface internal is lock long namespace new null object operator
out override params private protected public readonly ref return sbyte sealed short sizeof
stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe
ushort using virtual void volatile while""".split())


class CSharp(Lang):
    PRIM = {"string": "string", "integer": "long", "number": "double", "boolean": "bool",
            "null": "JsonElement", "any": "JsonElement", "object": "Dictionary<string, JsonElement>"}

    def t(self, tree, seen=()):
        tree, _ = self.split_null(tree)
        p = self.prim(tree)
        if p:
            return self.PRIM[p]
        kind = tree[0]
        if kind == "prim":
            return self.PRIM[tree[1]]
        if kind == "ref":
            tg = self.target(tree[1], seen)
            if tg[0] == "object":
                return tree[1]
            if tg[0] == "tree" and tree[1] not in seen:
                return self.t(tg[1], seen + (tree[1],))
            return "JsonElement"
        if kind == "array":
            return f"List<{self.t(tree[1], seen)}>"
        if kind == "record":
            return f"Dictionary<string, {self.t(tree[1], seen)}>"
        return "JsonElement"

    def render(self):
        out = [f"// {HEADER}", "#nullable enable", "using System.Collections.Generic;",
               "using System.Text.Json;", "using System.Text.Json.Serialization;", "",
               "namespace AlApi;", ""]
        for kind, name, doc, body in self.m.decls:
            out.append("/// <summary>" + doc_text(f"{doc}").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") + "</summary>")
            if kind == "object":
                fs = self.fields(body)

                def ident(n):
                    p = pascal(n) or "Field"
                    if not p[0].isalpha():
                        p = "_" + p
                    return p + ("Value" if p == name else "")
                idents = unique_names([f["name"] for f in fs], ident, {"Extra", name})
                out.append(f"public sealed record {name}")
                out.append("{")
                for f in fs:
                    tree, nullable = self.split_null(parse_type(f["type"]))
                    t = self.t(tree)
                    opt = f.get("optional") or nullable
                    req = "" if opt else "required "
                    out.append(f"    [JsonPropertyName({json.dumps(f['name'])})] public {req}{t}{'?' if opt else ''} "
                               f"{idents[f['name']]} {{ get; init; }}")
                if self.is_open(body):
                    out.append("    [JsonExtensionData] public Dictionary<string, JsonElement>? Extra { get; init; }")
                out.append("}")
            else:
                # Aliases and unions are inlined where they are used; the name is kept as a
                # comment so a reader can find it.
                what = body if kind == "alias" else " | ".join(body)
                out.append(f"// {name} = {what} (inlined at each use as {self.t(parse_type(what) if kind == 'alias' else ('union', [parse_type(x) for x in body]))})")
            out.append("")
        return "\n".join(out)


# ---------------------------------------------------------------------------------------------
# Rust: serde structs; type aliases; untagged enums for the declared unions
# ---------------------------------------------------------------------------------------------

RUST_KEYWORDS = set("""as break const continue crate else enum extern false fn for if impl in let
loop match mod move mut pub ref return self Self static struct super trait true type unsafe use
where while async await dyn abstract become box do final macro override priv typeof unsized
virtual yield try""".split())


def snake(name):
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name)
    s = re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_").lower() or "field"
    if s[0].isdigit():
        s = "n_" + s
    return "r#" + s if s in RUST_KEYWORDS and s not in ("self", "Self", "super", "crate") else (s + "_" if s in ("self", "super", "crate") else s)


class Rust(Lang):
    PRIM = {"string": "String", "integer": "i64", "number": "f64", "boolean": "bool",
            "null": "Value", "any": "Value", "object": "Map<String, Value>"}

    def t(self, tree):
        tree, nullable = self.split_null(tree)
        inner = self._t(tree)
        return f"Option<{inner}>" if nullable else inner

    def _t(self, tree):
        # String literals (and unions of them) become enums with one renamed unit variant per
        # value, so an untagged enum (a failure union) picks the variant whose `response` and
        # `place` really match, not the first one with a String there.
        strs = self.str_lits(tree)
        if strs:
            return self.lit_enum(strs)
        p = self.prim(tree)
        if p:
            return self.PRIM[p]
        kind = tree[0]
        if kind == "prim":
            return self.PRIM[tree[1]]
        if kind == "ref":
            return tree[1]
        if kind == "array":
            return f"Vec<{self.t(tree[1])}>"
        if kind == "record":
            return f"HashMap<String, {self.t(tree[1])}>"
        if kind == "tuple":
            return "(" + ", ".join(self.t(x) for x in tree[1]) + ("," if len(tree[1]) == 1 else "") + ")"
        return "Value"

    enums = None

    @staticmethod
    def str_lits(tree):
        if tree[0] == "lit" and isinstance(tree[1], str):
            return [tree[1]]
        if tree[0] == "union" and all(x[0] == "lit" and isinstance(x[1], str) for x in tree[1]):
            return list(dict.fromkeys(x[1] for x in tree[1]))
        return None

    def lit_enum(self, values):
        key = tuple(sorted(values))
        if key not in self.enums:
            base = "Lit" + "".join(pascal(v) or "Empty" for v in key[:3]) + ("Etc" if len(key) > 3 else "")
            name, i = base, 2
            while name in self.enum_names or name in self.objects or name in self.aliases or name in self.unions:
                name, i = f"{base}{i}", i + 1
            self.enum_names.add(name)
            self.enums[key] = (name, values)
        return self.enums[key][0]

    def enum_decls(self):
        out = []
        for name, values in self.enums.values():
            out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]")
            out.append(f"pub enum {name} {{")
            for i, v in enumerate(values):
                ident = pascal(v) or "Empty"
                if not ident[0].isalpha():
                    ident = "V" + ident
                out.append(f"    #[serde(rename = {json.dumps(v)})]")
                out.append(f"    {ident}{'' if ident not in [pascal(x) for x in values[:i]] else i},")
            out.append("}")
            out.append("")
        return out

    def render(self):
        self.enums, self.enum_names = {}, set()
        body = self.render_body()
        head = body[:body.index("")]
        return "\n".join(head + [""] + self.enum_decls() + body[len(head):])

    def render_body(self):
        out = [f"// {HEADER}", "#![allow(dead_code, non_camel_case_types, clippy::all)]",
               "use serde::{Deserialize, Serialize};", "use serde_json::{Map, Value};",
               "use std::collections::HashMap;", ""]
        for kind, name, doc, body in self.m.decls:
            out += wrap(doc, prefix="/// ")
            if kind == "object":
                fs = self.fields(body)
                idents = unique_names([f["name"] for f in fs], snake, {"extra"})
                out.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
                out.append(f"pub struct {name} {{")
                for f in fs:
                    tree, nullable = self.split_null(parse_type(f["type"]))
                    t = self._t(tree)
                    if t in self.objects:
                        # Box: a struct may not hold itself by value, also through a chain.
                        t = f"Box<{t}>"
                    attrs = [f"rename = {json.dumps(f['name'])}"]
                    if f.get("optional") or nullable:
                        t = f"Option<{t}>"
                        attrs += ["default", 'skip_serializing_if = "Option::is_none"']
                    out.append(f"    #[serde({', '.join(attrs)})]")
                    out.append(f"    pub {idents[f['name']]}: {t},")
                if self.is_open(body):
                    out.append("    /// The keys this struct does not name.")
                    out.append("    #[serde(flatten)]")
                    out.append("    pub extra: Map<String, Value>,")
                out.append("}")
            elif kind == "alias":
                t = self.t(parse_type(body))
                out.append(f"pub type {name} = {'Value' if t == name else t};")
            else:
                trees = [parse_type(x) for x in body]
                p = self.prim(("union", trees))
                if p:
                    out.append(f"pub type {name} = {self.PRIM[p]};")
                else:
                    # Untagged: serde tries each variant in order. Bare codes are one String.
                    out.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
                    out.append("#[serde(untagged)]")
                    out.append(f"pub enum {name} {{")
                    # Bare codes (string literals) are one variant: an enum of the codes.
                    codes = [v for tree in trees for v in (self.str_lits(tree) or [])]
                    for x, tree in zip(body, trees):
                        if tree[0] == "ref" and tree[1] in self.objects:
                            out.append(f"    {x}(Box<{x}>),")
                        elif tree[0] == "ref":
                            out.append(f"    {x}({self.t(tree)}),")
                        elif not self.str_lits(tree):
                            out.append(f"    V{pascal(x) or 'Value'}({self.t(tree)}),")
                    if codes:
                        out.append(f"    Code({self.lit_enum(list(dict.fromkeys(codes)))}),")
                    out.append("}")
            out.append("")
        return out


# ---------------------------------------------------------------------------------------------
# Java: records with Jackson annotations, nested in one class; aliases inlined; sealed
# interfaces for the declared unions of records
# ---------------------------------------------------------------------------------------------

JAVA_RESERVED = set("""abstract assert boolean break byte case catch char class const continue
default do double else enum extends final finally float for goto if implements import instanceof
int interface long native new package private protected public return short static strictfp
super switch synchronized this throw throws transient try void volatile while true false null
var yield record sealed permits getClass hashCode equals toString notify notifyAll wait clone
finalize""".split())


def camel(name):
    p = pascal(name)
    s = (p[:1].lower() + p[1:]) or "field"
    if s[0].isdigit():
        s = "n" + s
    return s + "_" if s in JAVA_RESERVED else s


class Java(Lang):
    PRIM = {"string": "String", "integer": "Long", "number": "Double", "boolean": "Boolean",
            "null": "JsonNode", "any": "JsonNode", "object": "Map<String, JsonNode>"}

    def t(self, tree, seen=()):
        tree, _ = self.split_null(tree)
        p = self.prim(tree)
        if p:
            return self.PRIM[p]
        kind = tree[0]
        if kind == "prim":
            return self.PRIM[tree[1]]
        if kind == "ref":
            tg = self.target(tree[1], seen)
            if tg[0] == "object":
                return tree[1]
            if tg[0] == "tree" and tree[1] not in seen:
                return self.t(tg[1], seen + (tree[1],))
            if tg[0] == "union" and self.sealed(tree[1]):
                return tree[1]
            return "JsonNode"
        if kind == "array":
            return f"List<{self.t(tree[1], seen)}>"
        if kind == "record":
            return f"Map<String, {self.t(tree[1], seen)}>"
        return "JsonNode"

    def sealed(self, name):
        """A declared union whose members are all records: a sealed interface."""
        return all(x in self.objects for x in self.unions[name])

    def render(self):
        impls = {}
        for name, members in self.unions.items():
            if self.sealed(name):
                for x in members:
                    impls.setdefault(x, []).append(name)
        out = [f"// {HEADER}", "package alapi;", "",
               "import com.fasterxml.jackson.annotation.JsonIgnoreProperties;",
               "import com.fasterxml.jackson.annotation.JsonInclude;",
               "import com.fasterxml.jackson.annotation.JsonProperty;",
               "import com.fasterxml.jackson.databind.JsonNode;", "import java.util.List;",
               "import java.util.Map;", "",
               "/** The types of the Adventure Land socket API, as nested records. */",
               "public final class AlApi {", "    private AlApi() {}", ""]
        for kind, name, doc, body in self.m.decls:
            out.append("    /** " + doc_text(doc).replace("*/", "* /").replace("@", "{@literal @}") + " */")
            if kind == "object":
                fs = self.fields(body)
                idents = unique_names([f["name"] for f in fs], camel)
                comps = [f"@JsonProperty({json.dumps(f['name'])}) {self.t(parse_type(f['type']))} {idents[f['name']]}"
                         for f in fs]
                ann = "@JsonInclude(JsonInclude.Include.NON_NULL)"
                if self.is_open(body):
                    ann += " @JsonIgnoreProperties(ignoreUnknown = true)"
                imp = f" implements {', '.join(impls[name])}" if name in impls else ""
                out.append(f"    {ann}")
                out.append(f"    public record {name}(" + (
                    "\n        " + ",\n        ".join(comps) + ")" if comps else ")") + f"{imp} {{}}")
            elif kind == "union" and self.sealed(name):
                out.append(f"    public sealed interface {name} permits {', '.join(dict.fromkeys(body))} {{}}")
            else:
                what = body if kind == "alias" else " | ".join(body)
                out.append(f"    // {name} = {what} (inlined at each use)")
            out.append("")
        out.append("}")
        return "\n".join(out) + "\n"


GENERATORS = {"python": Python, "go": Go, "csharp": CSharp, "rust": Rust, "java": Java}


def generate(lang, schema=None):
    schema = schema or apischema.Schema()
    if lang == "ts":
        return apischema.typescript(schema)
    return GENERATORS[lang](schema).render()


def main():
    args = sys.argv[1:]
    if "--all" in args:
        root = Path(args[args.index("--all") + 1])
        schema = apischema.Schema()
        for lang in LANGS:
            p = root / lang / FILES[lang]
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(generate(lang, schema))
            print(f"{p}")
        return
    lang = args[args.index("--lang") + 1] if "--lang" in args else "ts"
    if lang not in LANGS:
        raise SystemExit(f"--lang is one of {' '.join(LANGS)}")
    text = generate(lang)
    if "-o" in args:
        Path(args[args.index("-o") + 1]).write_text(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
